export const AR = {
  app_name: 'كلمات',
  daily_word: 'كلمة اليوم',
  speed_duel: 'تحدٍ سريع',
  classic: 'الكلاسيكي',
  leaderboard: 'المتصدرون',
  profile: 'ملفي',
  shop: 'المتجر',
  play_now: 'العب الآن',
  share_result: 'شارك النتيجة',
  try_again: 'حاول مجدداً',
  searching_opponent: 'جاري البحث عن منافس...',
  you_won: 'فزت! 🏆',
  you_lost: 'خسرت! 💪',
  streak: 'سلسلتك',
  days: 'أيام',
  attempts: 'محاولات',
  correct_answer: 'كان الجواب',
  come_back_tomorrow: 'عد غداً لكلمة جديدة',
  time_remaining: 'وقت متبقي',
  invalid_word: 'هذه الكلمة غير موجودة في القاموس',
  not_enough_letters: 'أكمل الكلمة أولاً',
  coins: 'عملات',
  hint: 'تلميح',
  use_hint: 'استخدم تلميحاً (20 عملة)',
  watch_ad_hint: 'شاهد إعلاناً للحصول على تلميح',
  plus_subscribe: 'اشترك في كلمات بلس',
  sign_in: 'سجل دخولك',
  guest_mode: 'العب كضيف',
  username: 'اسم المستخدم',
  save: 'حفظ',
  cancel: 'إلغاء',
  rematch: 'مباراة أخرى',
  friends: 'أصدقائي',
  today: 'اليوم',
  all_time: 'الكل',
  excellent: 'ممتاز!',
  try_tomorrow: 'حاول غداً',
  got_it_in: 'أصبت في',
  answer_was: 'كان الجواب',
  your_streak: 'سلسلتك',
  day_streak: 'يوم متتالي',
  play_free: 'العب مجاناً على كلمات',
  vs_computer: 'العب ضد الكمبيوتر',
  word_of_today: 'كلمات اليوم',
  global_solved: 'من اللاعبين أصابوا اليوم',
  best_streak: 'أفضل سلسلة',
  duels_won: 'مباريات فزت',
  avg_attempts: 'متوسط المحاولات',
  success_rate: 'نسبة النجاح',
  sounds: 'الأصوات',
  notifications: 'الإشعارات',
  sign_in_save: 'سجل دخولك لحفظ تقدمك',
  plus_banner: 'كلمات بلس — بدون إعلانات، مع تلميحات',
  enter: 'أدخل',
  consecutive_days: 'أيام متتالية',
  since: 'منذ',
  no_ads: 'بدون إعلانات',
  with_hints: 'مع تلميحات',
} as const;
