// English word lists for Kalimat — 5-letter words with categories

export interface EnglishWordEntry {
  word: string;
  category: string;
}

export const WORDS_EN_5: EnglishWordEntry[] = [
  // Animals
  { word: 'TIGER', category: 'animals' },
  { word: 'SHARK', category: 'animals' },
  { word: 'EAGLE', category: 'animals' },
  { word: 'HORSE', category: 'animals' },
  { word: 'WHALE', category: 'animals' },
  { word: 'SNAKE', category: 'animals' },
  { word: 'ZEBRA', category: 'animals' },
  { word: 'PANDA', category: 'animals' },
  { word: 'KOALA', category: 'animals' },
  { word: 'CAMEL', category: 'animals' },
  { word: 'RHINO', category: 'animals' },
  { word: 'BISON', category: 'animals' },
  { word: 'CRANE', category: 'animals' },
  { word: 'RAVEN', category: 'animals' },
  { word: 'TAPIR', category: 'animals' },
  { word: 'MOOSE', category: 'animals' },
  { word: 'GOOSE', category: 'animals' },
  { word: 'OTTER', category: 'animals' },
  { word: 'LLAMA', category: 'animals' },
  { word: 'HYENA', category: 'animals' },
  { word: 'HERON', category: 'animals' },
  { word: 'TROUT', category: 'animals' },
  { word: 'MOUSE', category: 'animals' },
  { word: 'STORK', category: 'animals' },

  // Food
  { word: 'BREAD', category: 'food' },
  { word: 'PIZZA', category: 'food' },
  { word: 'GRAPE', category: 'food' },
  { word: 'MANGO', category: 'food' },
  { word: 'LEMON', category: 'food' },
  { word: 'OLIVE', category: 'food' },
  { word: 'PEACH', category: 'food' },
  { word: 'PLUMB', category: 'food' },
  { word: 'STEAK', category: 'food' },
  { word: 'SUSHI', category: 'food' },
  { word: 'PASTA', category: 'food' },
  { word: 'TACOS', category: 'food' },
  { word: 'HONEY', category: 'food' },
  { word: 'SPICE', category: 'food' },
  { word: 'CREAM', category: 'food' },
  { word: 'ROAST', category: 'food' },
  { word: 'TOAST', category: 'food' },
  { word: 'SALAD', category: 'food' },
  { word: 'SAUCE', category: 'food' },
  { word: 'CANDY', category: 'food' },
  { word: 'MELON', category: 'food' },
  { word: 'BERRY', category: 'food' },
  { word: 'CURRY', category: 'food' },
  { word: 'BACON', category: 'food' },

  // Nature
  { word: 'STORM', category: 'nature' },
  { word: 'RIVER', category: 'nature' },
  { word: 'OCEAN', category: 'nature' },
  { word: 'FLAME', category: 'nature' },
  { word: 'FROST', category: 'nature' },
  { word: 'CLOUD', category: 'nature' },
  { word: 'STONE', category: 'nature' },
  { word: 'GROVE', category: 'nature' },
  { word: 'CLIFF', category: 'nature' },
  { word: 'THORN', category: 'nature' },
  { word: 'MARSH', category: 'nature' },
  { word: 'RIDGE', category: 'nature' },
  { word: 'DELTA', category: 'nature' },
  { word: 'CORAL', category: 'nature' },
  { word: 'FIELD', category: 'nature' },
  { word: 'BEACH', category: 'nature' },
  { word: 'EARTH', category: 'nature' },
  { word: 'OASIS', category: 'nature' },
  { word: 'SWAMP', category: 'nature' },
  { word: 'CREEK', category: 'nature' },
  { word: 'BLOOM', category: 'nature' },
  { word: 'CEDAR', category: 'nature' },
  { word: 'FLINT', category: 'nature' },
  { word: 'SLOPE', category: 'nature' },

  // Actions
  { word: 'CLIMB', category: 'actions' },
  { word: 'DANCE', category: 'actions' },
  { word: 'FIGHT', category: 'actions' },
  { word: 'GROWL', category: 'actions' },
  { word: 'SHINE', category: 'actions' },
  { word: 'SNEAK', category: 'actions' },
  { word: 'STEAL', category: 'actions' },
  { word: 'SWEEP', category: 'actions' },
  { word: 'THROW', category: 'actions' },
  { word: 'TWIST', category: 'actions' },
  { word: 'SLASH', category: 'actions' },
  { word: 'BLEND', category: 'actions' },
  { word: 'CHASE', category: 'actions' },
  { word: 'CRAWL', category: 'actions' },
  { word: 'GRASP', category: 'actions' },
  { word: 'LAUGH', category: 'actions' },
  { word: 'SHOUT', category: 'actions' },
  { word: 'SLIDE', category: 'actions' },
  { word: 'SMASH', category: 'actions' },
  { word: 'STARE', category: 'actions' },
  { word: 'SWIRL', category: 'actions' },
  { word: 'TEACH', category: 'actions' },
  { word: 'TRACE', category: 'actions' },
  { word: 'WHIRL', category: 'actions' },

  // Objects
  { word: 'BLADE', category: 'objects' },
  { word: 'CHAIN', category: 'objects' },
  { word: 'CHEST', category: 'objects' },
  { word: 'CLOCK', category: 'objects' },
  { word: 'CROWN', category: 'objects' },
  { word: 'GLOBE', category: 'objects' },
  { word: 'KNIFE', category: 'objects' },
  { word: 'LASER', category: 'objects' },
  { word: 'PRISM', category: 'objects' },
  { word: 'SHELF', category: 'objects' },
  { word: 'TORCH', category: 'objects' },
  { word: 'VAULT', category: 'objects' },
  { word: 'WHEEL', category: 'objects' },
  { word: 'FLUTE', category: 'objects' },
  { word: 'BADGE', category: 'objects' },
  { word: 'BRUSH', category: 'objects' },
  { word: 'FRAME', category: 'objects' },
  { word: 'PIANO', category: 'objects' },
  { word: 'PLATE', category: 'objects' },
  { word: 'RADAR', category: 'objects' },
  { word: 'SCALE', category: 'objects' },
  { word: 'SPEAR', category: 'objects' },
  { word: 'STRAP', category: 'objects' },
  { word: 'TOWER', category: 'objects' },

  // Traits
  { word: 'BRAVE', category: 'traits' },
  { word: 'CRUEL', category: 'traits' },
  { word: 'EAGER', category: 'traits' },
  { word: 'FIERY', category: 'traits' },
  { word: 'GIDDY', category: 'traits' },
  { word: 'PROUD', category: 'traits' },
  { word: 'SWIFT', category: 'traits' },
  { word: 'WITTY', category: 'traits' },
  { word: 'QUIET', category: 'traits' },
  { word: 'HAPPY', category: 'traits' },
  { word: 'NOBLE', category: 'traits' },
  { word: 'SHARP', category: 'traits' },
  { word: 'SMART', category: 'traits' },
  { word: 'STERN', category: 'traits' },
  { word: 'VIVID', category: 'traits' },
  { word: 'LOYAL', category: 'traits' },
  { word: 'NAIVE', category: 'traits' },
  { word: 'WISER', category: 'traits' },

  // Space / Science
  { word: 'COMET', category: 'science' },
  { word: 'DWARF', category: 'science' },
  { word: 'LUNAR', category: 'science' },
  { word: 'ORBIT', category: 'science' },
  { word: 'OZONE', category: 'science' },
  { word: 'QUARK', category: 'science' },
  { word: 'SOLAR', category: 'science' },
  { word: 'ATOMS', category: 'science' },
  { word: 'NERVE', category: 'science' },
  { word: 'PULSE', category: 'science' },
  { word: 'RADAR', category: 'science' },
  { word: 'VAPOR', category: 'science' },

  // Places
  { word: 'PLAZA', category: 'places' },
  { word: 'CABIN', category: 'places' },
  { word: 'ARENA', category: 'places' },
  { word: 'MANOR', category: 'places' },
  { word: 'ABBEY', category: 'places' },
  { word: 'ALLEY', category: 'places' },
  { word: 'DEPOT', category: 'places' },
  { word: 'LODGE', category: 'places' },
  { word: 'WHARF', category: 'places' },
  { word: 'PLAZA', category: 'places' },

  // Body
  { word: 'BRAIN', category: 'body' },
  { word: 'HEART', category: 'body' },
  { word: 'THUMB', category: 'body' },
  { word: 'SKULL', category: 'body' },
  { word: 'SPINE', category: 'body' },
  { word: 'ELBOW', category: 'body' },
  { word: 'WRIST', category: 'body' },
  { word: 'ANKLE', category: 'body' },

  // Time
  { word: 'EPOCH', category: 'time' },
  { word: 'MONTH', category: 'time' },
  { word: 'CLOCK', category: 'time' },
  { word: 'EARLY', category: 'time' },
  { word: 'HASTY', category: 'time' },

  // Everyday
  { word: 'WATER', category: 'everyday' },
  { word: 'HOUSE', category: 'everyday' },
  { word: 'TABLE', category: 'everyday' },
  { word: 'CHAIR', category: 'everyday' },
  { word: 'LIGHT', category: 'everyday' },
  { word: 'PHONE', category: 'everyday' },
  { word: 'SHIRT', category: 'everyday' },
  { word: 'SHOES', category: 'everyday' },
  { word: 'MONEY', category: 'everyday' },
  { word: 'MUSIC', category: 'everyday' },
  { word: 'DREAM', category: 'everyday' },
  { word: 'POWER', category: 'everyday' },
  { word: 'VOICE', category: 'everyday' },
  { word: 'PEACE', category: 'everyday' },
  { word: 'WORLD', category: 'everyday' },
  { word: 'STORY', category: 'everyday' },
  { word: 'TRUTH', category: 'everyday' },
  { word: 'MAGIC', category: 'everyday' },
  { word: 'ANGEL', category: 'everyday' },
  { word: 'GHOST', category: 'everyday' },
  { word: 'FOCUS', category: 'everyday' },
  { word: 'YOUTH', category: 'everyday' },
  { word: 'CHARM', category: 'everyday' },
  { word: 'FORCE', category: 'everyday' },
  { word: 'TRIAL', category: 'everyday' },
  { word: 'UNITY', category: 'everyday' },
  { word: 'VALUE', category: 'everyday' },
  { word: 'WORTH', category: 'everyday' },
  { word: 'SPACE', category: 'everyday' },
  { word: 'TRADE', category: 'everyday' },

  // More common words
  { word: 'ABOVE', category: 'everyday' },
  { word: 'AFTER', category: 'everyday' },
  { word: 'ALARM', category: 'everyday' },
  { word: 'ALBUM', category: 'everyday' },
  { word: 'ALIEN', category: 'everyday' },
  { word: 'ANGER', category: 'everyday' },
  { word: 'BASIC', category: 'everyday' },
  { word: 'BLACK', category: 'everyday' },
  { word: 'BLANK', category: 'everyday' },
  { word: 'BLAZE', category: 'everyday' },
  { word: 'BLOCK', category: 'everyday' },
  { word: 'BOARD', category: 'everyday' },
  { word: 'BONUS', category: 'everyday' },
  { word: 'BREAK', category: 'everyday' },
  { word: 'BRIEF', category: 'everyday' },
  { word: 'CARGO', category: 'everyday' },
  { word: 'CATCH', category: 'everyday' },
  { word: 'CAUSE', category: 'everyday' },
  { word: 'CHIEF', category: 'everyday' },
  { word: 'CLAIM', category: 'everyday' },
  { word: 'CLASH', category: 'everyday' },
  { word: 'CLEAN', category: 'everyday' },
  { word: 'CLEAR', category: 'everyday' },
  { word: 'COLOR', category: 'everyday' },
  { word: 'COUNT', category: 'everyday' },
  { word: 'COVER', category: 'everyday' },
  { word: 'CRAFT', category: 'everyday' },
  { word: 'CRASH', category: 'everyday' },
  { word: 'CREED', category: 'everyday' },
  { word: 'CROSS', category: 'everyday' },
  { word: 'CROWD', category: 'everyday' },
  { word: 'DAILY', category: 'everyday' },
  { word: 'DEATH', category: 'everyday' },
  { word: 'DEPTH', category: 'everyday' },
  { word: 'DODGE', category: 'everyday' },
  { word: 'DOUBT', category: 'everyday' },
  { word: 'DRAFT', category: 'everyday' },
  { word: 'DRAIN', category: 'everyday' },
  { word: 'DRESS', category: 'everyday' },
  { word: 'DRINK', category: 'everyday' },
  { word: 'DRIVE', category: 'everyday' },
  { word: 'DWELT', category: 'everyday' },
  { word: 'EASEL', category: 'everyday' },
  { word: 'EIGHT', category: 'everyday' },
  { word: 'ELITE', category: 'everyday' },
  { word: 'EMPTY', category: 'everyday' },
  { word: 'ENEMY', category: 'everyday' },
  { word: 'ENJOY', category: 'everyday' },
  { word: 'EQUAL', category: 'everyday' },
  { word: 'ERROR', category: 'everyday' },
  { word: 'EVENT', category: 'everyday' },
  { word: 'EVERY', category: 'everyday' },
  { word: 'EXACT', category: 'everyday' },
  { word: 'EXIST', category: 'everyday' },
  { word: 'EXTRA', category: 'everyday' },
  { word: 'FAINT', category: 'everyday' },
  { word: 'FAITH', category: 'everyday' },
  { word: 'FAVOR', category: 'everyday' },
  { word: 'FEAST', category: 'everyday' },
  { word: 'FIBER', category: 'everyday' },
  { word: 'FINAL', category: 'everyday' },
  { word: 'FIRST', category: 'everyday' },
  { word: 'FIXED', category: 'everyday' },
  { word: 'FLASH', category: 'everyday' },
  { word: 'FLESH', category: 'everyday' },
  { word: 'FLOOD', category: 'everyday' },
  { word: 'FLOOR', category: 'everyday' },
  { word: 'FLOUR', category: 'everyday' },
  { word: 'FLUID', category: 'everyday' },
  { word: 'FORGE', category: 'everyday' },
  { word: 'FRESH', category: 'everyday' },
  { word: 'FRONT', category: 'everyday' },
  { word: 'FRUIT', category: 'everyday' },
  { word: 'GIANT', category: 'everyday' },
  { word: 'GLASS', category: 'everyday' },
  { word: 'GLOOM', category: 'everyday' },
  { word: 'GLORY', category: 'everyday' },
  { word: 'GOING', category: 'everyday' },
  { word: 'GRACE', category: 'everyday' },
  { word: 'GRAIN', category: 'everyday' },
  { word: 'GRAND', category: 'everyday' },
  { word: 'GRANT', category: 'everyday' },
  { word: 'GRASS', category: 'everyday' },
  { word: 'GREAT', category: 'everyday' },
  { word: 'GREEN', category: 'everyday' },
  { word: 'GREED', category: 'everyday' },
  { word: 'GROUP', category: 'everyday' },
  { word: 'GUARD', category: 'everyday' },
  { word: 'GUESS', category: 'everyday' },
  { word: 'GUIDE', category: 'everyday' },
  { word: 'GUILD', category: 'everyday' },
  { word: 'HAVEN', category: 'everyday' },
  { word: 'HONOR', category: 'everyday' },
  { word: 'HUMAN', category: 'everyday' },
  { word: 'HUMOR', category: 'everyday' },
  { word: 'IMAGE', category: 'everyday' },
  { word: 'INDEX', category: 'everyday' },
  { word: 'INNER', category: 'everyday' },
  { word: 'INPUT', category: 'everyday' },
  { word: 'IRONY', category: 'everyday' },
  { word: 'IVORY', category: 'everyday' },
  { word: 'JEWEL', category: 'everyday' },
  { word: 'JOINT', category: 'everyday' },
  { word: 'JUDGE', category: 'everyday' },
  { word: 'JUICE', category: 'everyday' },
  { word: 'KNOWN', category: 'everyday' },
  { word: 'LABOR', category: 'everyday' },
  { word: 'LARGE', category: 'everyday' },
  { word: 'LAYER', category: 'everyday' },
  { word: 'LEARN', category: 'everyday' },
  { word: 'LEGAL', category: 'everyday' },
  { word: 'LEVEL', category: 'everyday' },
  { word: 'LIMIT', category: 'everyday' },
  { word: 'LINEN', category: 'everyday' },
  { word: 'LOCAL', category: 'everyday' },
  { word: 'LOGIC', category: 'everyday' },
  { word: 'LOVER', category: 'everyday' },
  { word: 'LOWER', category: 'everyday' },
  { word: 'LUCKY', category: 'everyday' },
  { word: 'MAJOR', category: 'everyday' },
  { word: 'MAKER', category: 'everyday' },
  { word: 'MATCH', category: 'everyday' },
  { word: 'MAYOR', category: 'everyday' },
  { word: 'MEDAL', category: 'everyday' },
  { word: 'MERCY', category: 'everyday' },
  { word: 'METAL', category: 'everyday' },
  { word: 'MIGHT', category: 'everyday' },
  { word: 'MINOR', category: 'everyday' },
  { word: 'MODEL', category: 'everyday' },
  { word: 'MORAL', category: 'everyday' },
  { word: 'MOUNT', category: 'everyday' },
  { word: 'NIGHT', category: 'everyday' },
  { word: 'NOISE', category: 'everyday' },
  { word: 'NORTH', category: 'everyday' },
  { word: 'NOVEL', category: 'everyday' },
  { word: 'OCCUR', category: 'everyday' },
  { word: 'OFFER', category: 'everyday' },
  { word: 'ORDER', category: 'everyday' },
  { word: 'OTHER', category: 'everyday' },
  { word: 'OUTER', category: 'everyday' },
  { word: 'OWNER', category: 'everyday' },
  { word: 'PAINT', category: 'everyday' },
  { word: 'PANEL', category: 'everyday' },
  { word: 'PARTY', category: 'everyday' },
  { word: 'PATCH', category: 'everyday' },
  { word: 'PAUSE', category: 'everyday' },
  { word: 'PHASE', category: 'everyday' },
  { word: 'PIECE', category: 'everyday' },
  { word: 'PILOT', category: 'everyday' },
  { word: 'PITCH', category: 'everyday' },
  { word: 'PLACE', category: 'everyday' },
  { word: 'PLAIN', category: 'everyday' },
  { word: 'PLANT', category: 'everyday' },
  { word: 'POINT', category: 'everyday' },
  { word: 'POUND', category: 'everyday' },
  { word: 'PRESS', category: 'everyday' },
  { word: 'PRICE', category: 'everyday' },
  { word: 'PRIDE', category: 'everyday' },
  { word: 'PRIME', category: 'everyday' },
  { word: 'PRINT', category: 'everyday' },
  { word: 'PRIZE', category: 'everyday' },
  { word: 'PROOF', category: 'everyday' },
  { word: 'QUEEN', category: 'everyday' },
  { word: 'QUEST', category: 'everyday' },
  { word: 'QUICK', category: 'everyday' },
  { word: 'QUOTE', category: 'everyday' },
  { word: 'RAISE', category: 'everyday' },
  { word: 'RANGE', category: 'everyday' },
  { word: 'RAPID', category: 'everyday' },
  { word: 'REACH', category: 'everyday' },
  { word: 'READY', category: 'everyday' },
  { word: 'REALM', category: 'everyday' },
  { word: 'REIGN', category: 'everyday' },
  { word: 'RIDER', category: 'everyday' },
  { word: 'RIGHT', category: 'everyday' },
  { word: 'RIVAL', category: 'everyday' },
  { word: 'ROBIN', category: 'everyday' },
  { word: 'ROCKY', category: 'everyday' },
  { word: 'ROUGH', category: 'everyday' },
  { word: 'ROUND', category: 'everyday' },
  { word: 'ROUTE', category: 'everyday' },
  { word: 'ROYAL', category: 'everyday' },
  { word: 'RURAL', category: 'everyday' },
  { word: 'SAINT', category: 'everyday' },
  { word: 'SCENE', category: 'everyday' },
  { word: 'SCENT', category: 'everyday' },
  { word: 'SCOPE', category: 'everyday' },
  { word: 'SENSE', category: 'everyday' },
  { word: 'SHAPE', category: 'everyday' },
  { word: 'SHELL', category: 'everyday' },
  { word: 'SHIFT', category: 'everyday' },
  { word: 'SIGHT', category: 'everyday' },
  { word: 'SKILL', category: 'everyday' },
  { word: 'SLEEP', category: 'everyday' },
  { word: 'SMALL', category: 'everyday' },
  { word: 'SMILE', category: 'everyday' },
  { word: 'SMOKE', category: 'everyday' },
  { word: 'SOLID', category: 'everyday' },
  { word: 'SOLVE', category: 'everyday' },
  { word: 'SOUND', category: 'everyday' },
  { word: 'SOUTH', category: 'everyday' },
  { word: 'SPARE', category: 'everyday' },
  { word: 'SPEAK', category: 'everyday' },
  { word: 'SPEED', category: 'everyday' },
  { word: 'SPEND', category: 'everyday' },
  { word: 'SPLIT', category: 'everyday' },
  { word: 'SPORT', category: 'everyday' },
  { word: 'STAFF', category: 'everyday' },
  { word: 'STAGE', category: 'everyday' },
  { word: 'STAKE', category: 'everyday' },
  { word: 'STAND', category: 'everyday' },
  { word: 'START', category: 'everyday' },
  { word: 'STATE', category: 'everyday' },
  { word: 'STEAM', category: 'everyday' },
  { word: 'STEEL', category: 'everyday' },
  { word: 'STEEP', category: 'everyday' },
  { word: 'STICK', category: 'everyday' },
  { word: 'STILL', category: 'everyday' },
  { word: 'STOCK', category: 'everyday' },
  { word: 'STRIP', category: 'everyday' },
  { word: 'STUDY', category: 'everyday' },
  { word: 'STUFF', category: 'everyday' },
  { word: 'STYLE', category: 'everyday' },
  { word: 'SUGAR', category: 'everyday' },
  { word: 'SUPER', category: 'everyday' },
  { word: 'SURGE', category: 'everyday' },
  { word: 'SWEET', category: 'everyday' },
  { word: 'SWING', category: 'everyday' },
  { word: 'SWORD', category: 'everyday' },
  { word: 'THEIR', category: 'everyday' },
  { word: 'THEME', category: 'everyday' },
  { word: 'THICK', category: 'everyday' },
  { word: 'THING', category: 'everyday' },
  { word: 'THINK', category: 'everyday' },
  { word: 'TIDAL', category: 'everyday' },
  { word: 'TIGHT', category: 'everyday' },
  { word: 'TIMER', category: 'everyday' },
  { word: 'TITLE', category: 'everyday' },
  { word: 'TOKEN', category: 'everyday' },
  { word: 'TOTAL', category: 'everyday' },
  { word: 'TOUGH', category: 'everyday' },
  { word: 'TRACK', category: 'everyday' },
  { word: 'TRAIN', category: 'everyday' },
  { word: 'TREND', category: 'everyday' },
  { word: 'TRICK', category: 'everyday' },
  { word: 'TROOP', category: 'everyday' },
  { word: 'TRUCK', category: 'everyday' },
  { word: 'TRUNK', category: 'everyday' },
  { word: 'TRUST', category: 'everyday' },
  { word: 'ULTRA', category: 'everyday' },
  { word: 'UNDER', category: 'everyday' },
  { word: 'UPPER', category: 'everyday' },
  { word: 'URBAN', category: 'everyday' },
  { word: 'USUAL', category: 'everyday' },
  { word: 'UTTER', category: 'everyday' },
  { word: 'VIGOR', category: 'everyday' },
  { word: 'VITAL', category: 'everyday' },
  { word: 'VOCAL', category: 'everyday' },
  { word: 'WASTE', category: 'everyday' },
  { word: 'WATCH', category: 'everyday' },
  { word: 'WEIRD', category: 'everyday' },
  { word: 'WHILE', category: 'everyday' },
  { word: 'WHITE', category: 'everyday' },
  { word: 'WHOLE', category: 'everyday' },
  { word: 'WOUND', category: 'everyday' },
  { word: 'WRITE', category: 'everyday' },
  { word: 'WRONG', category: 'everyday' },
  { word: 'YEARN', category: 'everyday' },
  { word: 'YIELD', category: 'everyday' },
];

// All valid 5-letter English guesses (superset includes answer words)
const VALID_GUESSES_SET = new Set<string>([
  ...WORDS_EN_5.map(w => w.word),
  'ABOUT', 'ABUSE', 'ACTOR', 'ACUTE', 'ADEPT', 'ADOBE', 'ADULT',
  'AGAIN', 'AGENT', 'AGILE', 'AGONY', 'AGREE', 'AHEAD', 'AISLE',
  'ALERT', 'ALGAE', 'ALIGN', 'ALIKE', 'ALIVE', 'ALLAY', 'ALLOW',
  'ALONE', 'ALONG', 'ALOOF', 'ALOUD', 'ALPHA', 'ALTAR', 'ALTER',
  'AMAZE', 'AMBER', 'AMEND', 'AMPLE', 'ANGLE', 'ANGRY', 'ANIME',
  'ANNEX', 'APART', 'APPLE', 'APPLY', 'ARGUE', 'ARISE', 'ARMOR',
  'AROMA', 'AROSE', 'ARRAY', 'ASIDE', 'ASKED', 'ATLAS', 'ATONE',
  'ATTIC', 'AUDIO', 'AUDIT', 'AVOID', 'AWAKE', 'AWARD', 'AWARE',
  'AWFUL', 'AXION', 'BADGE', 'BADLY', 'BAKER', 'BARON', 'BASIN',
  'BASIS', 'BATCH', 'BEGUN', 'BEING', 'BELOW', 'BENCH', 'BIRTH',
  'BLAND', 'BLAST', 'BLEED', 'BLESS', 'BLIND', 'BLISS', 'BLOWN',
  'BLUNT', 'BLUSH', 'BOOZE', 'BORED', 'BOUND', 'BRACE', 'BRAND',
  'BRASS', 'BREED', 'BRICK', 'BRIDE', 'BRING', 'BROAD', 'BROKE',
  'BROOK', 'BROWN', 'BUDDY', 'BUILD', 'BUILT', 'BUNCH', 'BURST',
  'BUYER', 'CABLE', 'CADET', 'CAMPS', 'CANAL', 'CASTE', 'CHALK',
  'CHANT', 'CHAOS', 'CHEAP', 'CHECK', 'CHEEK', 'CHEER', 'CHESS',
  'CHILD', 'CHILL', 'CHINA', 'CHOSE', 'CHUNK', 'CIVIC', 'CIVIL',
  'CLICK', 'CLIMB', 'CLING', 'CLONE', 'CLOSE', 'CLOTH', 'CLOWN',
  'COACH', 'COAST', 'COULD', 'COUCH', 'COUGH', 'COUPE', 'COURT',
  'CRANE', 'CREEK', 'CREST', 'CRISP', 'CUBIC', 'CURVE', 'CYCLE',
  'DEALS', 'DECAY', 'DEBUT', 'DECOR', 'DEITY', 'DEMON', 'DENSE',
  'DEPOT', 'DERBY', 'DIGIT', 'DITCH', 'DIZZY', 'DOING', 'DONOR',
  'DOZEN', 'DRAWN', 'DRIED', 'DROIT', 'DRONE', 'DROWN', 'DRUGS',
  'DRUMS', 'DRUNK', 'DRYLY', 'DUSTY', 'DWARF', 'DYING', 'EATEN',
  'EDICT', 'ELFIN', 'EMBER', 'ENSUE', 'ENTER', 'EPOCH', 'EQUIP',
  'ERASE', 'ETHIC', 'EVADE', 'EVOKE', 'EXCEL', 'EXILE', 'EXPEL',
  'FABLE', 'FACET', 'FAIRY', 'FALSE', 'FANCY', 'FATAL', 'FAULT',
  'FENCE', 'FETCH', 'FEVER', 'FIFTY', 'FILTH', 'FLAME', 'FLARE',
  'FLASK', 'FLEET', 'FLING', 'FLOAT', 'FLOCK', 'FOGGY', 'FORCE',
  'FORTY', 'FOUND', 'FRAIL', 'FRAUD', 'FREED', 'FRIAR', 'FROWN',
  'FROZE', 'FUNGI', 'FUZZY', 'GAMMA', 'GAUGE', 'GAVEL', 'GAZER',
  'GENRE', 'GIVEN', 'GLAND', 'GLEAM', 'GLIDE', 'GLINT', 'GLOAT',
  'GNOME', 'GOLEM', 'GRAFT', 'GRAVE', 'GRAZE', 'GRIEF', 'GRILL',
  'GRIND', 'GROAN', 'GROOM', 'GROSS', 'GROVE', 'GROWN', 'GRUEL',
  'GRUNT', 'GUISE', 'GULLY', 'GYPSY', 'HABIT', 'HAIKU', 'HASTE',
  'HAVEN', 'HEADY', 'HEFTY', 'HEIST', 'HENCE', 'HITCH', 'HOARD',
  'HOBBY', 'HOMER', 'HOUND', 'HOVER', 'HUMID', 'HURRY', 'HYPER',
  'IDEAL', 'IDIOT', 'IMPLY', 'INCUR', 'INDIE', 'INEPT', 'INFER',
  'INGOT', 'IRATE', 'ISSUE', 'JAUNT', 'JELLY', 'JOLLY', 'JOUST',
  'KEBAB', 'KNACK', 'KNAVE', 'KNEEL', 'KNELT', 'KNOCK', 'LABEL',
  'LANCE', 'LAPSE', 'LATCH', 'LATER', 'LADEN', 'LADLE', 'LEAPT',
  'LEASE', 'LEAVE', 'LEFTY', 'LEVER', 'LIBEL', 'LIKEN', 'LIMBO',
  'LOFTY', 'LORRY', 'LOTUS', 'LUCID', 'LUNGE', 'LUSTY', 'LYRIC',
  'MACHO', 'MAFIA', 'MAPLE', 'MARCH', 'MASON', 'MAXIM', 'MERCY',
  'MERGE', 'MERIT', 'METER', 'MIDST', 'MIMIC', 'MIRTH', 'MOIST',
  'MONEY', 'MOODY', 'MORON', 'MORPH', 'MOTIF', 'MOTOR', 'MOTTO',
  'MOUND', 'MOURN', 'MOVIE', 'MUCUS', 'MUDDY', 'MULTI', 'MUMMY',
  'MURAL', 'MUSHY', 'NAIVE', 'NASTY', 'NAVAL', 'NAVEL', 'NEEDY',
  'NICHE', 'NINNY', 'NOTCH', 'NUDGE', 'NURSE', 'NYLON', 'OCCUR',
  'OCEAN', 'ONSET', 'OPERA', 'OPTIC', 'OUNCE', 'OVARY', 'OVERT',
  'OXIDE', 'PAGAN', 'PANIC', 'PEARL', 'PENNY', 'PERCH', 'PERIL',
  'PETTY', 'PIXEL', 'PLANK', 'PLEAD', 'PLEAT', 'PLUCK', 'PLUMB',
  'PLUME', 'PLUMP', 'PLUSH', 'POKER', 'POLAR', 'POOCH', 'PORCH',
  'POSER', 'POUTY', 'PRAWN', 'PREEN', 'PRICK', 'PRIMP', 'PRONE',
  'PROXY', 'PRUDE', 'PRUNE', 'PUPIL', 'PURGE', 'PYGMY', 'QUALM',
  'QUERY', 'QUEUE', 'QUOTA', 'RABBI', 'RALLY', 'RAMPS', 'RANCH',
  'RAZOR', 'REBEL', 'REFER', 'REIGN', 'RELAX', 'REPAY', 'REPEL',
  'REPLY', 'RESIN', 'RETRY', 'REVUE', 'RIDGE', 'RIFLE', 'RIGOR',
  'RINSE', 'RISEN', 'RISKY', 'ROACH', 'ROBOT', 'ROGUE', 'ROVER',
  'RUGBY', 'RULER', 'RUMOR', 'RUPEE', 'RUSTY', 'SABOT', 'SADLY',
  'SALSA', 'SANDY', 'SATAY', 'SAUNA', 'SAVOR', 'SCALD', 'SCALY',
  'SCAMP', 'SCANT', 'SCARE', 'SCOFF', 'SCOLD', 'SCONE', 'SCORE',
  'SCOUT', 'SCRAM', 'SCRAP', 'SCRUB', 'SEIZE', 'SERVE', 'SETUP',
  'SEVEN', 'SHACK', 'SHADE', 'SHADY', 'SHALL', 'SHAME', 'SHARK',
  'SHAVE', 'SHAWL', 'SHEER', 'SHEET', 'SHORE', 'SHORT', 'SHOVE',
  'SHRUB', 'SIEGE', 'SINCE', 'SIXTH', 'SIXTY', 'SKATE', 'SKIMP',
  'SLACK', 'SLAIN', 'SLANG', 'SLATE', 'SLEEK', 'SLICE', 'SLIMY',
  'SLOTH', 'SMITH', 'SNAIL', 'SNARE', 'SNORE', 'SOLAR', 'SONIC',
  'SORRY', 'SPADE', 'SPANK', 'SPARK', 'SPAWN', 'SPECK', 'SPELL',
  'SPENT', 'SPILL', 'SPOKE', 'SPOON', 'SPRAY', 'SPREE', 'SQUAT',
  'SQUID', 'STAIN', 'STAIR', 'STALE', 'STALL', 'STAMP', 'STARK',
  'STEEP', 'STEER', 'STERN', 'STIFF', 'STING', 'STINK', 'STOLE',
  'STOMP', 'STOOD', 'STOOL', 'STOOP', 'STORE', 'STORM', 'STOUT',
  'STOVE', 'STRAY', 'STRUT', 'STUMP', 'STUNG', 'STUNK', 'STUNT',
  'SUAVE', 'SUITE', 'SUNNY', 'SWAMP', 'SWARM', 'SWEAR', 'SWEAT',
  'SWEPT', 'SWIPE', 'SWOON', 'SWORE', 'SWORN', 'SYRUP', 'TABOO',
  'TACKY', 'TAINT', 'TAKEN', 'TALLY', 'TALON', 'TANGO', 'TASTE',
  'TAUNT', 'TEMPO', 'TENSE', 'TEPID', 'THANK', 'THEFT', 'THERE',
  'THESE', 'THOSE', 'THREE', 'THREW', 'TIDAL', 'TIGER', 'TIPSY',
  'TODAY', 'TOXIC', 'TRAMP', 'TRASH', 'TRAWL', 'TREAT', 'TRIED',
  'TRITE', 'TROLL', 'TRUCE', 'TRULY', 'TRUMP', 'TUMOR', 'TUNIC',
  'TWANG', 'TWEAK', 'TWEED', 'TWEET', 'TWICE', 'TWIRL', 'UDDER',
  'ULCER', 'UNCUT', 'UNDUE', 'UNFIT', 'UNION', 'UNITE', 'UNTIL',
  'UPSET', 'USHER', 'VAGUE', 'VALID', 'VALVE', 'VAPID', 'VAULT',
  'VENUE', 'VERGE', 'VERSE', 'VIDEO', 'VIGIL', 'VINYL', 'VIOLA',
  'VIPER', 'VIRUS', 'VISIT', 'VISTA', 'VIVID', 'VIXEN', 'VODKA',
  'VOILA', 'VOTER', 'VOUCH', 'VOWEL', 'WACKY', 'WAGER', 'WAGON',
  'WAIST', 'WALTZ', 'WEARY', 'WEAVE', 'WEDGE', 'WHEAT', 'WHERE',
  'WHICH', 'WHIFF', 'WHINE', 'WHISK', 'WIDEN', 'WIDOW', 'WIDTH',
  'WITCH', 'WOMEN', 'WORSE', 'WORST', 'WRATH', 'WRECK', 'WRING',
  'WROTE', 'XENON', 'YACHT', 'YOUNG', 'ZEBRA', 'ZIPPY', 'ZOMBI',
  // Additional common words players would try
  'ABOVE', 'AFTER', 'ANGEL', 'BASIC', 'BEACH', 'BLACK', 'BLADE',
  'BLAME', 'BLANK', 'BLAZE', 'BLEND', 'BLOCK', 'BLOOD', 'BLOOM',
  'BOARD', 'BOOST', 'BRAIN', 'BRAVE', 'BREAK', 'BRIEF', 'BRUSH',
  'CABIN', 'CARRY', 'CHAIN', 'CHAIR', 'CHARM', 'CHASE', 'CHEST',
  'CIVIC', 'CLAMP', 'CLASP', 'CLASS', 'CLIFF', 'CLOCK', 'CLOUD',
  'COBRA', 'COMET', 'CORAL', 'CRACK', 'CRAZY', 'CROWN', 'CRUSH',
  'DANCE', 'DELAY', 'DIRTY', 'DOUGH', 'DRAMA', 'DRANK', 'DREAM',
  'DRINK', 'DRIVE', 'DROVE', 'EAGER', 'EARLY', 'EARTH', 'ENTER',
  'ENTRY', 'ESSAY', 'FACED', 'FALSE', 'FANCY', 'FEAST', 'FENCE',
  'FIELD', 'FIGHT', 'FINAL', 'FIRST', 'FIXED', 'FLOAT', 'FLOOR',
  'FLOUR', 'FOCUS', 'FORCE', 'FOUND', 'FRAME', 'FRESH', 'FRONT',
  'FROST', 'FROZE', 'FRUIT', 'FULLY', 'FUNNY', 'GIVEN', 'GLASS',
  'GLOBE', 'GOING', 'GRACE', 'GRADE', 'GRAND', 'GRANT', 'GRASP',
  'GRASS', 'GREAT', 'GREEN', 'GREET', 'GROUP', 'GROVE', 'GUARD',
  'GUESS', 'GUIDE', 'GUILT', 'HAPPY', 'HARSH', 'HEART', 'HEAVY',
  'HELLO', 'HORSE', 'HOTEL', 'HOUSE', 'HUMAN', 'HUMOR', 'HURRY',
  'IMAGE', 'INDEX', 'INNER', 'INPUT', 'ISSUE', 'IVORY', 'JEWEL',
  'JUDGE', 'JUICE', 'KNOWN', 'LASER', 'LATER', 'LAUGH', 'LAYER',
  'LEARN', 'LEAVE', 'LEGAL', 'LEVEL', 'LIGHT', 'LIMIT', 'LOCAL',
  'LODGE', 'LOGIC', 'LOOSE', 'LOVER', 'LOWER', 'LOYAL', 'LUCKY',
  'LUNAR', 'MAGIC', 'MAJOR', 'MAKER', 'MANOR', 'MAPLE', 'MATCH',
  'MAYOR', 'MEDIA', 'MERCY', 'MERIT', 'METAL', 'MIGHT', 'MINOR',
  'MODEL', 'MONEY', 'MONTH', 'MORAL', 'MOTOR', 'MOUNT', 'MOUSE',
  'MOVED', 'MOVIE', 'MUSIC', 'NAIVE', 'NERVE', 'NEVER', 'NIGHT',
  'NOBLE', 'NOISE', 'NORTH', 'NOTED', 'NOVEL', 'NURSE', 'OCCUR',
  'OCEAN', 'OFFER', 'OFTEN', 'ONSET', 'OPERA', 'ORBIT', 'ORDER',
  'OTHER', 'OUTER', 'OXIDE', 'OZONE', 'PAINT', 'PANEL', 'PANIC',
  'PAPER', 'PARTY', 'PASTA', 'PATCH', 'PAUSE', 'PEACE', 'PEARL',
  'PENNY', 'PHASE', 'PHONE', 'PHOTO', 'PIANO', 'PIECE', 'PILOT',
  'PIXEL', 'PIZZA', 'PLACE', 'PLAIN', 'PLANE', 'PLANT', 'PLATE',
  'PLAZA', 'PLEAD', 'PLUCK', 'PLUMB', 'PLUME', 'POINT', 'POLAR',
  'POPUP', 'POWER', 'PRESS', 'PRICE', 'PRIDE', 'PRIME', 'PRINT',
  'PRIOR', 'PRIZE', 'PROBE', 'PROOF', 'PROUD', 'PROVE', 'PROXY',
  'PULSE', 'PUNCH', 'PUPIL', 'PURGE', 'QUEEN', 'QUERY', 'QUEST',
  'QUEUE', 'QUICK', 'QUIET', 'QUOTA', 'QUOTE', 'RADAR', 'RADIO',
  'RAISE', 'RANGE', 'RAPID', 'RATIO', 'REACH', 'READY', 'REALM',
  'REBEL', 'REFER', 'REIGN', 'RELAX', 'REPLY', 'RIDER', 'RIDGE',
  'RIGHT', 'RISKY', 'RIVAL', 'RIVER', 'ROBOT', 'ROCKY', 'ROUGE',
  'ROUGH', 'ROUND', 'ROUTE', 'ROYAL', 'RUGBY', 'RULER', 'RURAL',
  'SADLY', 'SAINT', 'SALAD', 'SAUCE', 'SCALE', 'SCARE', 'SCENE',
  'SCOPE', 'SCORE', 'SCOUT', 'SEIZE', 'SENSE', 'SERVE', 'SETUP',
  'SEVEN', 'SHADE', 'SHAKE', 'SHALL', 'SHAME', 'SHAPE', 'SHARE',
  'SHARK', 'SHARP', 'SHELF', 'SHELL', 'SHIFT', 'SHINE', 'SHIRT',
  'SHOCK', 'SHORT', 'SHOUT', 'SIGHT', 'SINCE', 'SIXTH', 'SKILL',
  'SLASH', 'SLATE', 'SLAVE', 'SLEEP', 'SLICE', 'SLIDE', 'SLOPE',
  'SMART', 'SMELL', 'SMILE', 'SNAKE', 'SOLAR', 'SOLID', 'SOLVE',
  'SOUND', 'SOUTH', 'SPACE', 'SPARE', 'SPARK', 'SPEAK', 'SPEED',
  'SPEND', 'SPICE', 'SPIKE', 'SPINE', 'SPITE', 'SPLIT', 'SPOKE',
  'SPOON', 'SPORT', 'SPRAY', 'SQUAD', 'STACK', 'STAFF', 'STAGE',
  'STAND', 'STARK', 'START', 'STATE', 'STAYS', 'STEAL', 'STEAM',
  'STEEL', 'STEEP', 'STEER', 'STONE', 'STOOD', 'STOOL', 'STOOP',
  'STORE', 'STORM', 'STORY', 'STRAP', 'STRAW', 'STRIP', 'STUCK',
  'STUDY', 'STUFF', 'STUMP', 'STYLE', 'SUGAR', 'SUITE', 'SUNNY',
  'SUPER', 'SURGE', 'SWAMP', 'SWEAR', 'SWEEP', 'SWEET', 'SWEPT',
  'SWIFT', 'SWING', 'SWORD', 'SWORN', 'TABLE', 'TASTE', 'TEACH',
  'TEARS', 'TEMPO', 'TENSE', 'TENTH', 'TERMS', 'THEME', 'THICK',
  'THING', 'THINK', 'THIRD', 'THORN', 'THOSE', 'TIGER', 'TIGHT',
  'TIMER', 'TIRED', 'TITLE', 'TODAY', 'TOKEN', 'TOOTH', 'TOTAL',
  'TOUCH', 'TOUGH', 'TOWER', 'TOXIC', 'TRACK', 'TRADE', 'TRAIL',
  'TRAIN', 'TRAIT', 'TRASH', 'TREAD', 'TREAT', 'TREND', 'TRIAL',
  'TRIBE', 'TRICK', 'TRIED', 'TROOP', 'TROVE', 'TRUCK', 'TRULY',
  'TRUST', 'TRUTH', 'TUMOR', 'TUNER', 'TWIST', 'ULTRA', 'UNCLE',
  'UNDER', 'UNION', 'UNITY', 'UNTIL', 'UPPER', 'UPSET', 'URBAN',
  'USAGE', 'USHER', 'VALID', 'VALUE', 'VAULT', 'VENUE', 'VERSE',
  'VIGOR', 'VIRAL', 'VIRUS', 'VISOR', 'VISIT', 'VITAL', 'VIVID',
  'VOCAL', 'VOICE', 'VOTER', 'WAGER', 'WASTE', 'WATCH', 'WATER',
  'WEARY', 'WEAVE', 'WEIRD', 'WHALE', 'WHERE', 'WHICH', 'WHILE',
  'WHOLE', 'WHOSE', 'WIDER', 'WITCH', 'WORLD', 'WORRY', 'WORSE',
  'WORST', 'WORTH', 'WOULD', 'WRATH', 'WRITE', 'WRONG', 'YACHT',
  'YEARN', 'YIELD', 'YOUNG', 'YOURS', 'YOUTH', 'ZEBRA', 'ZESTY',
  // More valid guesses (less common but players try them)
  'AAHED', 'ABACK', 'ABASH', 'ABATE', 'ABBEY', 'ABBOT', 'ABHOR',
  'ABIDE', 'ABLER', 'ABODE', 'ABYSS', 'ACIDS', 'ACHED', 'ACHES',
  'ACORN', 'ACRES', 'ACTED', 'ADAGE', 'ADDED', 'ADDER', 'AFOOT',
  'AGLOW', 'AIDED', 'AIMED', 'AIRED', 'AMBLE', 'AMONG', 'AMUSE',
  'ANVIL', 'APHID', 'APTLY', 'ARDOR', 'ARTSY', 'ASSAY', 'AXLES',
  'AZURE', 'BADLY', 'BAGEL', 'BALMS', 'BALMY', 'BANJO', 'BARON',
  'BASIL', 'BASIN', 'BEADS', 'BEARD', 'BEDEW', 'BEGUN', 'BELLS',
  'BERTH', 'BIBLE', 'BIKES', 'BILLS', 'BIRCH', 'BIRDS', 'BITES',
  'BLOWN', 'BLUES', 'BLUFF', 'BLUNT', 'BLURT', 'BLUSH', 'BOATS',
  'BOGUS', 'BOLTS', 'BONDS', 'BONES', 'BOOKS', 'BOOTS', 'BORED',
  'BOTCH', 'BOUGH', 'BOUND', 'BOXER', 'BRAWL', 'BRIBE', 'BROIL',
  'BROOD', 'BROTH', 'BROWS', 'BRUNT', 'BULLY', 'BUMPY', 'BUNNY',
  'BURNS', 'BUSHY', 'BYWAY', 'CALLS', 'CAMPS', 'CANAL', 'CAULK',
  'CEDAR', 'CENTS', 'CHAFE', 'CHALK', 'CHANT', 'CHASM', 'CHEER',
  'CHEWY', 'CHIDE', 'CHIVE', 'CHOIR', 'CHOSE', 'CHUNK', 'CINCH',
  'CIVIC', 'CIVIL', 'CLANG', 'CLANK', 'CLAPS', 'CLEFT', 'CLERK',
  'CLICK', 'CLIMB', 'CLING', 'CLINK', 'CLOAK', 'CLONE', 'CLOSE',
  'CLOTH', 'CLOUT', 'COALS', 'COAST', 'COILS', 'COINS', 'COMFY',
  'CONCH', 'CONDO', 'COOKED','COPSE', 'CORES', 'CORNY', 'COSTS',
  'COUCH', 'COUGH', 'COULD', 'COUNT', 'COURT', 'COVER', 'COVET',
  'CRABS', 'CRAFT', 'CRANK', 'CRASH', 'CRAWL', 'CREEK', 'CRIMP',
  'CRISP', 'CROAK', 'CROOK', 'CROPS', 'CROSS', 'CROWD', 'CRUMB',
  'CRUSH', 'CURLY', 'CURRY', 'CURVE', 'CYCLE', 'DADDY', 'DAILY',
  'DAISY', 'DARKS', 'DATES', 'DAUNT', 'DEALT', 'DEATH', 'DECAY',
  'DECKS', 'DEMON', 'DENSE', 'DEPOT', 'DEPTH', 'DERBY', 'DETER',
  'DIARY', 'DIGIT', 'DINER', 'DIRTY', 'DISCO', 'DITCH', 'DITTY',
  'DIZZY', 'DODGE', 'DOING', 'DOLLS', 'DONOR', 'DOORS', 'DOSES',
  'DOUBT', 'DOUGH', 'DOZEN', 'DRAFT', 'DRAIN', 'DRAKE', 'DRAMA',
  'DRANK', 'DRAPE', 'DRAWN', 'DREAM', 'DRIED', 'DRIFT', 'DRILL',
  'DRINK', 'DRIVE', 'DRONE', 'DROPS', 'DROVE', 'DROWN', 'DRUMS',
  'DRUNK', 'DRYER', 'DUCKS', 'DUMBS', 'DUNKS', 'DUSTY', 'DWARF',
  'DWELL', 'DYING', 'EATEN', 'EDGES', 'EERIE', 'EIGHT', 'ELBOW',
  'ELDER', 'ELECT', 'ELITE', 'EMBED', 'EMCEE', 'EMOTE', 'EMPTY',
  'ENDOW', 'ENEMY', 'ENJOY', 'ENSUE', 'ENTER', 'ENTRY', 'ENVOY',
  'EQUAL', 'EQUIP', 'ERASE', 'ERROR', 'ESSAY', 'ETHIC', 'EVADE',
  'EVENT', 'EVERY', 'EVICT', 'EVOKE', 'EXACT', 'EXAMS', 'EXCEL',
  'EXILE', 'EXIST', 'EXPEL', 'EXTRA', 'EXUDE', 'FABLE', 'FACET',
  'FACTS', 'FAINT', 'FAIRY', 'FAITH', 'FALLS', 'FALSE', 'FAMED',
  'FANCY', 'FANGS', 'FARCE', 'FATAL', 'FAULT', 'FAUNA', 'FEAST',
  'FEELS', 'FENCE', 'FERAL', 'FETCH', 'FEVER', 'FIBER', 'FIELD',
  'FIEND', 'FIERY', 'FIFTY', 'FIGHT', 'FILTH', 'FINAL', 'FINDS',
  'FIRST', 'FLAIR', 'FLAKE', 'FLAME', 'FLANK', 'FLARE', 'FLASH',
  'FLASK', 'FLAWS', 'FLECK', 'FLESH', 'FLICK', 'FLIES', 'FLING',
  'FLINT', 'FLIRT', 'FLOAT', 'FLOCK', 'FLOOD', 'FLOOR', 'FLORA',
  'FLOSS', 'FLOUR', 'FLOUT', 'FLOWS', 'FLUID', 'FLUSH', 'FLUTE',
  'FOCAL', 'FOCUS', 'FOGGY', 'FOLDS', 'FOLKS', 'FOLLY', 'FOODS',
  'FORCE', 'FORGE', 'FORMS', 'FORTH', 'FORTY', 'FORUM', 'FOUND',
  'FOYER', 'FRAIL', 'FRAME', 'FRANK', 'FRAUD', 'FREED', 'FRESH',
  'FRIAR', 'FRIED', 'FRIES', 'FRONT', 'FROST', 'FROZE', 'FRUIT',
  'FULLY', 'FUNDS', 'FUNGI', 'FUNKY', 'FUNNY', 'FURRY', 'FUSSY',
  'FUZZY', 'GAMMA', 'GANGS', 'GAUGE', 'GAUZE', 'GAVEL', 'GAZER',
  'GEARS', 'GEESE', 'GENRE', 'GHOST', 'GIANT', 'GIFTS', 'GIDDY',
  'GIRLS', 'GIRTH', 'GIVEN', 'GIVES', 'GLAND', 'GLARE', 'GLEAM',
  'GLEAN', 'GLIDE', 'GLINT', 'GLOAT', 'GLOBE', 'GLOOM', 'GLORY',
  'GLOSS', 'GLOVE', 'GNASH', 'GNOME', 'GOALS', 'GOING', 'GOLDEN',
  'GOLEM', 'GOODS', 'GOOSE', 'GORGE', 'GRACE', 'GRADE', 'GRAFT',
  'GRAIN', 'GRAND', 'GRANT', 'GRAPE', 'GRAPH', 'GRASP', 'GRASS',
  'GRATE', 'GRAVE', 'GRAVY', 'GRAZE', 'GREAT', 'GREED', 'GREEN',
  'GREET', 'GRIEF', 'GRILL', 'GRIND', 'GROAN', 'GROOM', 'GROPE',
  'GROSS', 'GROUP', 'GROVE', 'GROWL', 'GROWN', 'GRUEL', 'GRUNT',
  'GUARD', 'GUESS', 'GUEST', 'GUIDE', 'GUILD', 'GUILT', 'GUISE',
  'GULLY', 'GUSTO', 'GUSTY', 'GYPSY', 'HABIT', 'HAIKU', 'HALLS',
  'HANDS', 'HANDY', 'HAPPY', 'HARDY', 'HAREM', 'HARSH', 'HASTE',
  'HASTY', 'HATCH', 'HAUNT', 'HAVEN', 'HEADS', 'HEADY', 'HEARD',
  'HEART', 'HEAVY', 'HEDGE', 'HEFTY', 'HEIST', 'HELLO', 'HENCE',
  'HERBS', 'HILLS', 'HINGE', 'HIPPO', 'HIRED', 'HITCH', 'HOARD',
  'HOBBY', 'HOLDS', 'HOLES', 'HOMER', 'HOMES', 'HONOR', 'HORNS',
  'HORSE', 'HOTEL', 'HOUND', 'HOURS', 'HOUSE', 'HOVER', 'HUMAN',
  'HUMID', 'HUMOR', 'HURRY', 'HYENA', 'HYPER', 'IDEAL', 'IDEAS',
  'IDIOT', 'IGLOO', 'IMAGE', 'IMPLY', 'INANE', 'INCUR', 'INDIE',
  'INEPT', 'INERT', 'INFER', 'INGOT', 'INKED', 'INLET', 'INNER',
  'INPUT', 'INTER', 'INTRO', 'IRATE', 'IRONY', 'IVORY', 'JAUNT',
  'JAZZY', 'JEANS', 'JELLY', 'JERKY', 'JIFFY', 'JOKER', 'JOLLY',
  'JOUST', 'JUDGE', 'JUICE', 'JUICY', 'JUMBO', 'JUMPS', 'JUMPY',
  'KARMA', 'KAYAK', 'KEBAB', 'KEEPS', 'KICKS', 'KILLS', 'KINDS',
  'KINGS', 'KIOSK', 'KNACK', 'KNAVE', 'KNEEL', 'KNELT', 'KNOBS',
  'KNOCK', 'KNOLL', 'KNOTS', 'KNOWN', 'KNOWS', 'KUDOS', 'LABEL',
  'LABOR', 'LACKS', 'LADEN', 'LADLE', 'LANCE', 'LANDS', 'LANES',
  'LANKY', 'LAPEL', 'LAPSE', 'LARGE', 'LASER', 'LASTS', 'LATCH',
  'LATER', 'LAUGH', 'LAWNS', 'LAYER', 'LEADS', 'LEAFY', 'LEAPS',
  'LEAPT', 'LEARN', 'LEASE', 'LEAST', 'LEAVE', 'LEFTY', 'LEGAL',
  'LEMON', 'LEVEL', 'LEVER', 'LIBEL', 'LIGHT', 'LIKED', 'LIKEN',
  'LIKES', 'LIMBO', 'LIMIT', 'LINED', 'LINEN', 'LINER', 'LINES',
  'LINKS', 'LISTS', 'LIVED', 'LIVER', 'LIVES', 'LLAMA', 'LOADS',
  'LOBBY', 'LOCAL', 'LOCKS', 'LODGE', 'LOFTY', 'LOGIC', 'LOOKS',
  'LOOSE', 'LORDS', 'LORRY', 'LOSES', 'LOTUS', 'LOVED', 'LOVER',
  'LOVES', 'LOWER', 'LOYAL', 'LUCID', 'LUCKY', 'LUNAR', 'LUNCH',
  'LUNGE', 'LUSTY', 'LYING', 'LYRIC', 'MACHO', 'MAFIA', 'MAGIC',
  'MAGNA', 'MAJOR', 'MAKER', 'MAKES', 'MALES', 'MANOR', 'MAPLE',
  'MARCH', 'MARKS', 'MASON', 'MATCH', 'MATES', 'MAXIM', 'MAYOR',
  'MEALS', 'MEANS', 'MEANT', 'MEDAL', 'MEDIA', 'MELEE', 'MERCY',
  'MERGE', 'MERIT', 'MERRY', 'METAL', 'METER', 'MICRO', 'MIDST',
  'MIGHT', 'MILES', 'MILLS', 'MIMIC', 'MINDS', 'MINED', 'MINER',
  'MINES', 'MINOR', 'MINUS', 'MIRTH', 'MISTY', 'MIXED', 'MIXER',
  'MODEL', 'MODES', 'MOIST', 'MOLDY', 'MONEY', 'MONKS', 'MONTH',
  'MOODS', 'MOODY', 'MOOSE', 'MORAL', 'MORON', 'MORPH', 'MOSSY',
  'MOTIF', 'MOTOR', 'MOTTO', 'MOUND', 'MOUNT', 'MOURN', 'MOUSE',
  'MOUTH', 'MOVED', 'MOVER', 'MOVES', 'MOVIE', 'MUCUS', 'MUDDY',
  'MUMMY', 'MURAL', 'MUSHY', 'MUSIC', 'MUSTY', 'MYTHS', 'NAIVE',
  'NAMED', 'NAMES', 'NASTY', 'NAVAL', 'NAVEL', 'NEEDY', 'NERVE',
  'NEVER', 'NEWLY', 'NICHE', 'NIGHT', 'NINNY', 'NOBLE', 'NODES',
  'NOISE', 'NOISY', 'NORTH', 'NOTCH', 'NOTED', 'NOTES', 'NOVEL',
  'NUDGE', 'NURSE', 'NYLON', 'OASIS', 'OCCUR', 'OCEAN', 'ODDLY',
  'OFFER', 'OFTEN', 'OLIVE', 'ONSET', 'OPENS', 'OPERA', 'OPTIC',
  'ORBIT', 'ORDER', 'OTHER', 'OTTER', 'OUGHT', 'OUNCE', 'OUTER',
  'OVARY', 'OVERT', 'OWNED', 'OWNER', 'OXIDE', 'OZONE', 'PACED',
  'PACKS', 'PAGAN', 'PAGES', 'PAINS', 'PAINT', 'PAIRS', 'PALMS',
  'PANEL', 'PANIC', 'PANTS', 'PAPAL', 'PAPER', 'PARKS', 'PARTS',
  'PARTY', 'PASTA', 'PASTE', 'PATCH', 'PATHS', 'PATIO', 'PAUSE',
  'PAVED', 'PEACE', 'PEACH', 'PEAKS', 'PEARL', 'PEDAL', 'PENAL',
  'PENNY', 'PERCH', 'PERIL', 'PERKY', 'PETAL', 'PETTY', 'PHASE',
  'PHONE', 'PHOTO', 'PIANO', 'PICKS', 'PIECE', 'PILES', 'PILLS',
  'PILOT', 'PINES', 'PIXEL', 'PIXIE', 'PIZZA', 'PLACE', 'PLAID',
  'PLAIN', 'PLANE', 'PLANS', 'PLANT', 'PLATE', 'PLAYS', 'PLAZA',
  'PLEAD', 'PLEAT', 'PLIED', 'PLOTS', 'PLUCK', 'PLUMB', 'PLUME',
  'PLUMP', 'PLUMS', 'PLUSH', 'POETS', 'POINT', 'POISE', 'POKER',
  'POLAR', 'POLES', 'POLLS', 'PONDS', 'POOLS', 'POPUP', 'PORCH',
  'POSED', 'POSER', 'POSES', 'POSTS', 'POUCH', 'POUND', 'POUTY',
  'POWER', 'PRAWN', 'PRAYS', 'PRESS', 'PRICE', 'PRICK', 'PRIDE',
  'PRIME', 'PRINT', 'PRIOR', 'PRIVY', 'PRIZE', 'PROBE', 'PRONE',
  'PROOF', 'PROSE', 'PROUD', 'PROVE', 'PROXY', 'PRUDE', 'PRUNE',
  'PULLS', 'PULSE', 'PUMPS', 'PUNCH', 'PUPIL', 'PURGE', 'PURSE',
  'PYGMY', 'QUALM', 'QUEEN', 'QUERY', 'QUEST', 'QUEUE', 'QUICK',
  'QUIET', 'QUITE', 'QUOTA', 'QUOTE', 'RABBI', 'RABID', 'RACES',
  'RACKS', 'RADAR', 'RADIO', 'RAIDS', 'RAILS', 'RAINY', 'RAISE',
  'RALLY', 'RAMPS', 'RANCH', 'RANGE', 'RANKS', 'RAPID', 'RATED',
  'RATES', 'RATIO', 'RAYON', 'RAZOR', 'REACH', 'READS', 'READY',
  'REALM', 'REBEL', 'RECUT', 'REEDY', 'REFER', 'REFIT', 'REIGN',
  'RELAX', 'RELAY', 'RENEW', 'REPAY', 'REPEL', 'REPLY', 'RESIN',
  'RETRY', 'RIDER', 'RIDES', 'RIDGE', 'RIFLE', 'RIGOR', 'RIGID',
  'RINGS', 'RINSE', 'RISEN', 'RISES', 'RISKY', 'RITES', 'RIVAL',
  'RIVER', 'ROADS', 'ROAST', 'ROBES', 'ROBOT', 'ROCKS', 'ROCKY',
  'ROLES', 'ROLLS', 'ROMAN', 'ROOMS', 'ROOTS', 'ROPES', 'ROUGE',
  'ROUGH', 'ROUND', 'ROUTE', 'ROVER', 'ROWDY', 'ROYAL', 'RUDDY',
  'RUGBY', 'RULED', 'RULER', 'RULES', 'RUMOR', 'RUPEE', 'RURAL',
  'RUSTY', 'SABER', 'SABOT', 'SADLY', 'SAINT', 'SAINT', 'SALAD',
  'SALES', 'SALSA', 'SALVE', 'SALVO', 'SANDS', 'SANDY', 'SASSY',
  'SATAY', 'SAUNA', 'SAVED', 'SAVOR', 'SCALE', 'SCALD', 'SCALP',
  'SCAMP', 'SCANT', 'SCARE', 'SCENE', 'SCENT', 'SCOFF', 'SCOLD',
  'SCONE', 'SCOPE', 'SCORE', 'SCORN', 'SCOUT', 'SCRAM', 'SCRAP',
  'SCRUB', 'SEEDS', 'SEIZE', 'SENSE', 'SERVE', 'SETUP', 'SEVEN',
  'SHACK', 'SHADE', 'SHADY', 'SHAKE', 'SHALL', 'SHAME', 'SHAPE',
  'SHARE', 'SHARK', 'SHARP', 'SHAVE', 'SHAWL', 'SHEDS', 'SHEEN',
  'SHEER', 'SHEET', 'SHELF', 'SHELL', 'SHIFT', 'SHINE', 'SHINY',
  'SHIPS', 'SHIRT', 'SHOCK', 'SHOES', 'SHONE', 'SHOOK', 'SHOOT',
  'SHOPS', 'SHORE', 'SHORN', 'SHORT', 'SHOTS', 'SHOUT', 'SHOVE',
  'SHOWN', 'SHOWS', 'SHREW', 'SHRUB', 'SHRUG', 'SIDED', 'SIDES',
  'SIEGE', 'SIGMA', 'SIGNS', 'SILLY', 'SINCE', 'SITES', 'SIXTH',
  'SIXTY', 'SIZED', 'SIZES', 'SKATE', 'SKIMP', 'SKINS', 'SKIRT',
  'SKULL', 'SKUNK', 'SLACK', 'SLAIN', 'SLANG', 'SLANT', 'SLASH',
  'SLATE', 'SLAVE', 'SLEEK', 'SLEEP', 'SLEPT', 'SLICE', 'SLIDE',
  'SLIMY', 'SLING', 'SLOPE', 'SLOTH', 'SLUMP', 'SLUNK', 'SMACK',
  'SMALL', 'SMART', 'SMASH', 'SMEAR', 'SMELL', 'SMILE', 'SMITE',
  'SMITH', 'SMOCK', 'SMOKE', 'SMOKY', 'SNACK', 'SNAIL', 'SNAKE',
  'SNARE', 'SNARL', 'SNEAK', 'SNIDE', 'SNIFF', 'SNORE', 'SNOUT',
  'SNOWY', 'SNUCK', 'SOBER', 'SOCKS', 'SOGGY', 'SOLAR', 'SOLID',
  'SOLVE', 'SONGS', 'SONIC', 'SORRY', 'SORTS', 'SOULS', 'SOUND',
  'SOUTH', 'SPACE', 'SPADE', 'SPANK', 'SPARE', 'SPARK', 'SPAWN',
  'SPEAK', 'SPEAR', 'SPECK', 'SPEED', 'SPELL', 'SPEND', 'SPENT',
  'SPICE', 'SPICY', 'SPIED', 'SPIKE', 'SPILL', 'SPINE', 'SPITE',
  'SPLIT', 'SPOKE', 'SPOON', 'SPORT', 'SPOTS', 'SPRAY', 'SPREE',
  'SPUNK', 'SQUAD', 'SQUAT', 'SQUID', 'STACK', 'STAFF', 'STAGE',
  'STAID', 'STAIN', 'STAIR', 'STAKE', 'STALE', 'STALL', 'STAMP',
  'STAND', 'STANK', 'STARE', 'STARK', 'STARS', 'START', 'STASH',
  'STATE', 'STAYS', 'STEAD', 'STEAK', 'STEAL', 'STEAM', 'STEED',
  'STEEL', 'STEEP', 'STEER', 'STEMS', 'STEPS', 'STERN', 'STEWS',
  'STICK', 'STIFF', 'STILL', 'STING', 'STINK', 'STINT', 'STOCK',
  'STOIC', 'STOKE', 'STOLE', 'STOMP', 'STONE', 'STOOD', 'STOOL',
  'STOOP', 'STOPS', 'STORE', 'STORM', 'STORY', 'STOUT', 'STOVE',
  'STRAP', 'STRAW', 'STRAY', 'STRIP', 'STRUT', 'STUCK', 'STUDY',
  'STUFF', 'STUMP', 'STUNG', 'STUNK', 'STUNT', 'STYLE', 'SUAVE',
  'SUGAR', 'SUITE', 'SUITS', 'SULKY', 'SUNNY', 'SUPER', 'SURGE',
  'SURLY', 'SWAMP', 'SWARM', 'SWEAR', 'SWEAT', 'SWEEP', 'SWEET',
  'SWEPT', 'SWIFT', 'SWINE', 'SWING', 'SWIPE', 'SWIRL', 'SWOON',
  'SWOOP', 'SWORD', 'SWORE', 'SWORN', 'SWUNG', 'SYRUP', 'TABOO',
  'TACKY', 'TAINT', 'TAKEN', 'TAKES', 'TALES', 'TALKS', 'TALLY',
  'TALON', 'TANGO', 'TANKS', 'TAPES', 'TASKS', 'TASTE', 'TASTY',
  'TAUNT', 'TAXES', 'TEACH', 'TEAMS', 'TEARS', 'TEENS', 'TEETH',
  'TEMPO', 'TENDS', 'TENSE', 'TENTH', 'TENTS', 'TEPID', 'TERMS',
  'TESTS', 'THANK', 'THEFT', 'THEME', 'THERE', 'THESE', 'THICK',
  'THIEF', 'THIGH', 'THING', 'THINK', 'THIRD', 'THORN', 'THOSE',
  'THREE', 'THREW', 'THROW', 'THUMP', 'TIDAL', 'TIGER', 'TIGHT',
  'TILES', 'TILTS', 'TIMER', 'TIMES', 'TIMID', 'TIPSY', 'TIRED',
  'TITAN', 'TITLE', 'TOAST', 'TODAY', 'TOKEN', 'TOLLS', 'TONES',
  'TOOLS', 'TOOTH', 'TOPSY', 'TORCH', 'TORSO', 'TOTAL', 'TOTEM',
  'TOUCH', 'TOUGH', 'TOURS', 'TOWEL', 'TOWER', 'TOWNS', 'TOXIC',
  'TRACE', 'TRACK', 'TRADE', 'TRAIL', 'TRAIN', 'TRAIT', 'TRAMP',
  'TRAPS', 'TRASH', 'TRAWL', 'TREAD', 'TREAT', 'TREES', 'TREND',
  'TRIAL', 'TRIBE', 'TRICK', 'TRIED', 'TRIES', 'TRIMS', 'TRIPS',
  'TRITE', 'TROLL', 'TROOP', 'TROVE', 'TRUCE', 'TRUCK', 'TRULY',
  'TRUMP', 'TRUNK', 'TRUST', 'TRUTH', 'TRYST', 'TUBES', 'TUCKS',
  'TULIP', 'TUMOR', 'TUNES', 'TUNER', 'TUNIC', 'TURBO', 'TURNS',
  'TUTOR', 'TWANG', 'TWEAK', 'TWEED', 'TWEET', 'TWICE', 'TWIGS',
  'TWILL', 'TWINE', 'TWINS', 'TWIRL', 'TWIST', 'TYING', 'TYPED',
  'TYPES', 'TYPOS', 'UDDER', 'ULCER', 'ULTRA', 'UNCLE', 'UNCUT',
  'UNDER', 'UNDUE', 'UNDID', 'UNFIT', 'UNIFY', 'UNION', 'UNITE',
  'UNITS', 'UNITY', 'UNLIT', 'UNTIE', 'UNTIL', 'UNZIP', 'UPPER',
  'UPSET', 'URBAN', 'URGED', 'USAGE', 'USHER', 'USING', 'USUAL',
  'USURP', 'UTTER', 'VAGUE', 'VALID', 'VALOR', 'VALUE', 'VALVE',
  'VAPID', 'VAULT', 'VEINS', 'VENOM', 'VENUE', 'VERGE', 'VERSE',
  'VICAR', 'VIDEO', 'VIEWS', 'VIGIL', 'VIGOR', 'VINYL', 'VIOLA',
  'VIPER', 'VIRAL', 'VIRUS', 'VISOR', 'VISIT', 'VISTA', 'VITAL',
  'VIVID', 'VIXEN', 'VODKA', 'VOCAL', 'VOICE', 'VOILA', 'VOTER',
  'VOTES', 'VOUCH', 'VOWEL', 'VROOM', 'WACKY', 'WAGED', 'WAGER',
  'WAGES', 'WAGON', 'WAIST', 'WALKS', 'WALLS', 'WALTZ', 'WANTS',
  'WARDS', 'WARNS', 'WASTE', 'WATCH', 'WATER', 'WAVES', 'WAVED',
  'WEARY', 'WEAVE', 'WEDGE', 'WEEKS', 'WEIGH', 'WEIRD', 'WELLS',
  'WHALE', 'WHEAT', 'WHEEL', 'WHERE', 'WHICH', 'WHIFF', 'WHILE',
  'WHINE', 'WHIRL', 'WHISK', 'WHITE', 'WHOLE', 'WHOSE', 'WIDEN',
  'WIDER', 'WIDOW', 'WIDTH', 'WIELD', 'WIMPY', 'WINCE', 'WINDS',
  'WINES', 'WINGS', 'WIRED', 'WIRES', 'WITCH', 'WITTY', 'WOKEN',
  'WOMEN', 'WONKY', 'WOODS', 'WOOZY', 'WORDS', 'WORKS', 'WORLD',
  'WORMY', 'WORRY', 'WORSE', 'WORST', 'WORTH', 'WOULD', 'WOUND',
  'WRATH', 'WRECK', 'WRING', 'WRIST', 'WRITE', 'WRONG', 'WROTE',
  'WRUNG', 'WRYLY', 'YACHT', 'YARDS', 'YEARN', 'YEARS', 'YEAST',
  'YIELD', 'YOUNG', 'YOURS', 'YOUTH', 'YUCKY', 'ZAPPY', 'ZEBRA',
  'ZESTY', 'ZILCH', 'ZINGY', 'ZIPPY', 'ZONAL', 'ZONES',
]);

/**
 * Get daily English word deterministically from date string
 */
export function getDailyWordEN(date: string): EnglishWordEntry {
  let hash = 0;
  for (let i = 0; i < date.length; i++) {
    const char = date.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash;
  }
  return WORDS_EN_5[Math.abs(hash) % WORDS_EN_5.length];
}

/**
 * Get a random English word for duel/classic mode
 */
export function getRandomEnglishWord(): EnglishWordEntry {
  return WORDS_EN_5[Math.floor(Math.random() * WORDS_EN_5.length)];
}

/**
 * Get category for English daily word
 */
export function getDailyWordCategoryEN(date: string): string {
  return getDailyWordEN(date).category;
}

/**
 * Validate an English guess
 */
export function isValidEnglishWord(word: string): boolean {
  if (word.length === 0) return false;
  return VALID_GUESSES_SET.has(word.toUpperCase());
}
